#
# Makefile for Menu Program
#

CC_PTHREAD_FLAGS			 = -lpthread
CC_FLAGS                     = -c 
CC_OUTPUT_FLAGS				 = -o
CC                           = gcc
RM                           = rm
RM_FLAGS                     = -f

TARGET  =	main 
OBJS    =   main.c

all:
	$(CC) $(OBJS) $(CC_OUTPUT_FLAGS) $(TARGET)  

clean:
	   rm main,main~ 
